import React from 'react';
import { format } from 'date-fns';

const IncidentReportPDF = ({ incident, isPreview = false, printFriendly = false }) => {
    const submissionDate = format(new Date(), 'PPP p');
    const sectionHeaderClass = printFriendly 
        ? 'border-b-2 border-slate-800 pb-1 mb-2 font-bold text-slate-800' 
        : 'bg-slate-700 text-white font-bold p-2 rounded-t-md';

    const sectionBodyClass = printFriendly ? 'pt-1' : 'p-3 border border-t-0 border-slate-200 rounded-b-md';

    const gridItemClass = "py-2";
    
    return (
        <div className={`bg-white text-slate-800 p-8 font-sans text-sm ${isPreview ? '' : 'w-[210mm] min-h-[297mm]'}`}>
            {/* Header */}
            <div className="flex justify-between items-start pb-4 border-b-2 border-slate-800 mb-4">
                <div>
                    <h1 className="text-3xl font-bold text-slate-800">Incident Report</h1>
                    <p className="text-slate-600">Confidential | For Internal Use Only</p>
                </div>
                <div className="text-right">
                    <p className="font-semibold">Incident ID:</p>
                    <p className="font-mono bg-slate-100 px-2 py-1 rounded text-base">{incident.id || 'N/A'}</p>
                </div>
            </div>
            
            {/* Sub-header */}
            <div className="flex justify-between text-xs text-slate-500 mb-6">
                <span>Report Generated By: {incident.reporterName}</span>
                <span>Submission Date: {submissionDate}</span>
            </div>

            {/* Incident Details Section */}
            <div className="mb-6">
                <h2 className={sectionHeaderClass}>Incident Details</h2>
                <div className={sectionBodyClass}>
                    <div className="grid grid-cols-3 gap-x-6">
                        <div className={gridItemClass}>
                            <p className="font-semibold text-slate-500">Date of Incident</p>
                            <p>{format(new Date(incident.date), 'PPP')}</p>
                        </div>
                        <div className={gridItemClass}>
                            <p className="font-semibold text-slate-500">Time of Incident</p>
                            <p>{incident.time}</p>
                        </div>
                        <div className={gridItemClass}>
                            <p className="font-semibold text-slate-500">Incident Type</p>
                            <p className="font-bold">{incident.type}</p>
                        </div>
                        <div className={gridItemClass}>
                            <p className="font-semibold text-slate-500">Mine</p>
                            <p>{incident.mine}</p>
                        </div>
                        <div className={gridItemClass}>
                            <p className="font-semibold text-slate-500">Section</p>
                            <p>{incident.sectionName === 'Other' ? incident.otherSection : incident.sectionName}</p>
                        </div>
                        <div className={gridItemClass}>
                            <p className="font-semibold text-slate-500">Specific Location</p>
                            <p>{incident.location}</p>
                        </div>
                    </div>
                </div>
            </div>
            
            {/* Description Section */}
            <div className="mb-6">
                <h2 className={sectionHeaderClass}>Description of Incident</h2>
                <div className={sectionBodyClass}>
                    <p className="whitespace-pre-wrap">{incident.description}</p>
                </div>
            </div>

            {/* Victim Details Section */}
            {incident.victimDetails && (
                 <div className="mb-6">
                    <h2 className={sectionHeaderClass}>Personnel / Equipment Involved</h2>
                    <div className={sectionBodyClass}>
                        <p className="whitespace-pre-wrap">{incident.victimDetails}</p>
                    </div>
                </div>
            )}

            {/* Photos Section */}
            {incident.photos && incident.photos.length > 0 && (
                <div className="mb-6" style={{ pageBreakInside: 'avoid' }}>
                    <h2 className={sectionHeaderClass}>Attached Photos</h2>
                    <div className={`${sectionBodyClass} grid grid-cols-2 gap-4`}>
                        {incident.photos.map((photo, index) => (
                            <div key={index}>
                                <img src={photo.url} alt={`Attachment ${index + 1}`} className="max-w-full h-auto border rounded" />
                                <p className="text-xs text-center mt-1">{photo.name}</p>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Footer */}
            <div className="text-center text-xs text-slate-400 pt-4 mt-8 border-t">
                <p>This report was generated by the Mine Safety Reporter application.</p>
            </div>
        </div>
    );
};

export default IncidentReportPDF;
